INSERT INTO departments (name)
VALUES
    ('Front of House'),
    ('Back of House'),
    ('Sales'),
    ('Human Resources');

INSERT INTO role (title, salary, department_id)
VALUES
    ('Front of House Manager', 43000, 1),
    ('Back of House Manager', 43000, 2),
    ('Sales Manager', 50000, 3),
    ('HR Manager', 50000, 4),
    ('Cashier', 25000, 1),
    ('Salesperson', 25000, 1),
    ('Customer Experience', 25000, 1),
    ('Front Supervisor', 33000, 1),
    ('Truck Unload Associate', 25000, 2),
    ('Restock Expert', 25000, 2),
    ('Back Supervisor', 33000, 2),
    ('Product Procurement Associate', 40000, 3),
    ('Client Relations Associate', 40000, 3),
    ('Recruiter', 40000, 4),
    ('Employee Relations Associate', 40000, 4),
    ('Payroll Associate', 40000, 4);

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES
    ('Disney', 'Quaffle', 1, null),
('Embry', 'Lopez', 2, null),
('Nancy', 'Smith', 3, null),
('Rob', 'Lowe', 4, null),
('Barnes', 'Thomas', 13, 3),
('Campbell', 'Wanda', 5, 4),
('Lois', 'Thomas', 11, 3),
('Jesse', 'Allen', 16, 4),
('Patterson', 'Roberts', 7, 3),
('Henry', 'Gerald', 14, 4),
('Michelle', 'Stephen', 5, 1),
('Wilson', 'Allen', 10, 4),
('Morgan', 'Teresa', 13, 1),
('Henry', 'Jacqueline', 7, 1),
('Simmons', 'Thomas', 13, 2),
('Patterson', 'Sanchez', 7, 4),
('Rogers', 'Long', 10, 4),
('Henry', 'Gerald', 13, 4),
('Barnes', 'Carter', 14, 2),
('Ernest', 'Ralph', 7, 4),
('Barnes', 'Sanchez', 16, 3),
('Wilson', 'Long', 9, 4),
('Rogers', 'Long', 5, 4),
('Ross', 'Nelson', 11, 4),
('Lois', 'Ruth', 16, 1),
('Henry', 'Carlos', 16, 1),
('Jesse', 'Joseph', 14, 3),
('Reed', 'Clark', 5, 3),
('Patterson', 'Torres', 10, 1),
('Cook', 'Long', 10, 2),
('Jesse', 'Carlos', 16, 1),
('Frank', 'Clark', 10, 4),
('Shirley', 'Sanchez', 14, 2),
('Henry', 'Jean', 7, 1),
('Butler', 'Carlos', 16, 2),
('Michelle', 'Carlos', 6, 4),
('Michelle', 'Teresa', 7, 4),
('Jesse', 'Torres', 9, 4),
('Albert', 'Carter', 13, 1),
('Perry', 'Sanchez', 12, 4),
('Randy', 'Roberts', 11, 2),
('Bruce', 'Carlos', 16, 1),
('Bruce', 'Ralph', 13, 2),
('Larry', 'Allen', 15, 4),
('Larry', 'Wanda', 11, 4),
('Jesse', 'Carter', 12, 2),
('Frank', 'Alexander', 9, 1),
('Jesse', 'Carlos', 14, 4),
('Albert', 'Amanda', 16, 4),
('Walker', 'Jean', 16, 3);